### ISSUE TITLE
Compatibility with ios 6

### ISSUE THREAD

**Issue by fenomenar9** [donobono/DoActionSheet#3]
I thank you for your work but i wonder why you decide to make it compatible io7 or greater.
In fact , all you have to do is change the method getTextHeight to be compatible with io6:
- (double)getTextHeight:(UILabel *)lbText
  {
  CGSize constraintSize = CGSizeMake(lbText.frame.size.width , MAXFLOAT);
  CGSize labelSize = CGSizeZero;
  UIFont *newFont = [UIFont fontWithName:lbText.font.fontName size:lbText.font.pointSize];
  UILabel *gettingSizeLabel = [[UILabel alloc] init];
  gettingSizeLabel.font = newFont;
  gettingSizeLabel.text = lbText.text;
  gettingSizeLabel.textAlignment = lbText.textAlignment;
  gettingSizeLabel.lineBreakMode = lbText.lineBreakMode;
  labelSize = [gettingSizeLabel sizeThatFits:constraintSize];
  return ceil(labelSize.height);
  }

My Best Regards.

**Comment by donobono** [comment]
I added getting height code for iOS6. 

Actually, there was no special reason to support only iOS7, just I missed this code.. ^^;;
